name: ift6758-conda-env
channels:
  - defaults
dependencies:
  - python>=3.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - requests
  - opencv
  - tqdm
  - lxml
  - plotly
  - setuptools
  - ipykernel
  - ipywidgets
  - jupyterlab>=3.0.0
  - ipdb
  - wandb
  - plotly
  - scikit-learn
  - imbalanced-learn
